name: Docs Test

on:
  pull_request:
    branches: [main]
    paths:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website-mintlify.yml"
      - ".github/workflows/docs-check-broken-links.yml"
  push:
    branches: [main]
    paths:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website-mintlify.yml"
      - ".github/workflows/docs-check-broken-links.yml"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  docs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install packages and dependencies for all tests
        run: |
          uv pip install --system pytest-cov>=5
      - name: Install base package
        run: |
          uv pip install --system -e "."
      - name: Install packages and dependencies for Documentation
        run: |
          uv pip install --system pydoc-markdown pyyaml termcolor nbclient
          # Pin databind packages as version 4.5.0 is not compatible with pydoc-markdown.
          uv pip install --system databind.core==4.4.2 databind.json==4.4.2
      # Force reinstall specific versions to fix typing-extensions import error in CI
      - name: Force install specific versions of typing-extensions and pydantic
        run: |
          uv pip uninstall --system -y typing_extensions typing-extensions || true
          uv pip install --system --force-reinstall "typing-extensions==4.7.1"
          uv pip install --system --force-reinstall "pydantic<2.0"
      - name: List all installed packages and their versions
        run: |
          uv pip list
      - name: Run documentation tests
        run: |
          bash scripts/test.sh test/website/test_process_api_reference.py test/website/test_process_notebooks.py -m "not openai"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
